version: '3.8'
services:
  proxy:
    image: edgd1er/nordvpn-proxy:latest
    restart: unless-stopped
    ports:
      - "1080:1080" #socks proxy port
      - "8888:8888" #http proxy port
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # disable ipv6
    cap_add:
      - NET_ADMIN               # Required
    environment:
      - TZ=America/Chicago
      - COUNTRY=uk
      - GROUP=P2P
      - CYBER_SEC=off
      - TECHNOLOGY=NordLynx
      - DEBUG=false
      - NORDVPN_USER=<email> #Not required if using secrets
      - NORDVPN_PASS=<pass> #Not required if using secrets
    secrets:
      - NORDVPN_LOGIN
      - NORDVPN_PASS

secrets:
  NORDVPN_LOGIN:
    file: ./nordvpn_login
  NORDVPN_PASS:
    file: ./nordvpn_pwd